from models import db, Grapes, ParentRegions, SubRegions, User, grapes_subregions
from app import app

if __name__ == '__main__':
    with app.app_context():
        print("Building Database...")

        db.create_all()

        # Clear existing data
        db.session.query(grapes_subregions).delete()
        db.session.query(Grapes).delete()
        db.session.query(ParentRegions).delete()
        db.session.query(SubRegions).delete()
        db.session.query(User).delete()


        g1 = Grapes(name="Cabernet Sauvignon", color='Red', image='../public/cabernetsauvignon.jpg')
        g2 = Grapes(name="Chardonnay", color='White', image='../public/chardonnay.jpeg')
        g3 = Grapes(name="Riesling", color='White', image='../public/Riesling.jpg')
        g4 = Grapes(name="Pinot Noir", color='Red', image='../public/pinotnoir.jpg')
        g5 = Grapes(name="Sauvignon Blanc", color='White', image='../public/sauvignon-blanc.jpg')
        g6 = Grapes(name="Rkatsiteli", color='White', image='../public/Rkatsiteli.jpg')
        g7 = Grapes(name="Nebbiolo", color='Red', image='../public/nebbiolo.jpg')
        g8 = Grapes(name='Syrah', color='Red', image='../public/Syrah.jpg')
        g9 = Grapes(name='Pinot Grigio', color='White', image='../public/Pinot_Grigio.jpg')
        g10 = Grapes(name='Grenache', color='Red', image='../public/Grenachejpg.jpg')
        g11 = Grapes(name='Muscat', color='White', image='../public/muscat.jpg')
        g12 = Grapes(name='Saperavi', color='Red', image='../public/Saperavi.jpg')
        g13 = Grapes(name='Cabernet Franc', color='Red', image='../public/cabernetfranc.jpg')
        g14 = Grapes(name='Sangiovese', color='Red', image='../public/sangiovese.jpg')
        g15 = Grapes(name='Semillon', color='White', image='../public/semillon.jpg')
        g16 = Grapes(name='Pinot Blanc', color='Red', image='../public/pinotblanc.jpg')
        g17 = Grapes(name='Zinfandel', color='Red', image='../public/Zinfandel.jpg')
        g18 = Grapes(name='Merlot', color='Red', image='../public/merlot.jpg')
        g19 = Grapes(name='Colombard', color='White', image='../public/Colombard.jpg')
        g20 = Grapes(name='Chenin Blanc', color='Red', image='../public/Chenin.jpg')
        g21 = Grapes(name='Alicante Bouschet', color='Red', image='../public/alicante-bouschet.jpg')
        g22 = Grapes(name='Agiortiko', color='Red', image='../public/agiorgitiko.jpg')
        g23 = Grapes(name='Malbec', color='Red', image='../public/Malbec.jpg')
        g24 = Grapes(name='Barbera', color='Red', image='../public/Barbera.jpg')
        g25 = Grapes(name='Dolcetto', color='Red', image='../public/Dolcetto.jpg')
        g26 = Grapes(name='Blaufränkisch', color='Red', image='../public/blaufrankisch.jpeg')
        g27 = Grapes(name='Carménère', color='Red', image='../public/carmenere.jpg')
        g28 = Grapes(name='Grüner Veltliner', color='White', image='../public/gruner.jpeg')
        g29 = Grapes(name='Montepulciano', color='Red', image='../public/Montepulciano.jpg')
        g30 = Grapes(name='Mourvèdre', color='Red', image='../public/mourvedre.jpg')
        g31 = Grapes(name='Nero d\'Avola', color='Red', image='../public/nerodavola.jpg')
        g32 = Grapes(name='Petite Syrah', color='Red', image='../public/petitsyrah.jpg')
        g33 = Grapes(name='Tempranillo', color='Red', image='../public/tempranillo.jpg')
        g34 = Grapes(name='Marselan', color='Red', image='../public/marselan.jpg')
        g35 = Grapes(name='Carignan', color='Red', image='../public/carignan.jpg')
        g36 = Grapes(name='Albariño', color='White', image='../public/albarinho.jpg')
        g37 = Grapes(name='Furmint', color='White', image='../public/Furmint.jpg')
        g38 = Grapes(name='Cortese', color='White', image='../public/cortese.jpg')
        g39 = Grapes(name='Glera', color='White', image='../public/glera.jpg')
        g40 = Grapes(name='Charbono', color='Red', image='../public/charbono.jpg')
        g41 = Grapes(name='Marsanne', color='White', image='../public/marsanne.jpg')
        g42 = Grapes(name='Roussanne', color='White', image='../public/Roussanne.jpg')
        g43 = Grapes(name='Petit Manseng', color='White', image='../public/petitmanseng.jpg')
        g44 = Grapes(name='Verdejo', color='White', image='../public/verdejo.jpg')
        g45 = Grapes(name='Lambrusco', color='Red', image='../public/lambrusco.jpg')
        g46 = Grapes(name='Gamay', color='Red', image='../public/gamay.jpg')
        g47 = Grapes(name='Xinomavro', color='Red', image='../public/xinomavro.jpg')
        g48 = Grapes(name='Xarelo-lo', color='White', image='../public/xarello.jpg')
        g49 = Grapes(name='Macabeo', color='White', image='../public/macabeo.jpg')
        g50 = Grapes(name='Parellada', color='White', image='../public/parellada.jpg')
        g51 = Grapes(name='Hondarrabi Zuri', color='White', image='../public/hondarribi-zuri.jpg')
        g52 = Grapes(name='Hondarrabi Beltza', color='Red', image='../public/beltza.jpg')
        g53 = Grapes(name='Muscadet', color='White', image='../public/muscadet.jpg')
        g54 = Grapes(name='Kisi', color='White', image='../public/kisi.jpg')
        g55 = Grapes(name='Tsoulikouri', color='White', image='../public/tsoulikouri.jpg')
        g56 = Grapes(name='Aladasturi', color='Red', image='../public/aladasturi.jpg')
        g57 = Grapes(name='Dzelshavi', color='Red', image='../public/dzelshavi.jpg')
        g58 = Grapes(name='Tsitska', color='White', image='../public/tsitska.jpg')
        g59 = Grapes(name='Krakhuna', color='White', image='../public/krakhuna.jpg')
        g60 = Grapes(name='Chinuri', color='White', image='../public/chinuri.jpg')
        g61 = Grapes(name='Chinuri', color='White', image='../public/chinuri.jpg')




        pr1 = ParentRegions(name="California", country='USA')
        pr2 = ParentRegions(name="Oregon", country='USA')  
        pr3 = ParentRegions(name="New York", country='USA')  
        pr4 = ParentRegions(name="Virginia", country='USA')
        pr5 = ParentRegions(name="Washington", country='USA')
        pr6 = ParentRegions(name="Colorado", country='USA')
        pr7 = ParentRegions(name="Connecticut", country='USA')
        pr8 = ParentRegions(name="Delaware", country='USA')
        pr9 = ParentRegions(name="Florida", country='USA')
        pr10 = ParentRegions(name="Georgia", country='USA')
        pr11 = ParentRegions(name="Hawaii", country='USA')
        pr12 = ParentRegions(name="Idaho", country='USA')
        pr13 = ParentRegions(name="Illinois", country='USA')
        pr14 = ParentRegions(name="Indiana", country='USA')
        pr15 = ParentRegions(name="Iowa", country='USA')
        pr16 = ParentRegions(name="Kansas", country='USA')
        pr17 = ParentRegions(name="Kentucky", country='USA')
        pr18 = ParentRegions(name="Louisiana", country='USA')
        pr19 = ParentRegions(name="Maine", country='USA')
        pr20 = ParentRegions(name="Maryland", country='USA')
        pr21 = ParentRegions(name="Massachusetts", country='USA')
        pr22 = ParentRegions(name="Michigan", country='USA')
        pr23 = ParentRegions(name="Minnesota", country='USA')
        pr24 = ParentRegions(name="Mississippi", country='USA')
        pr25 = ParentRegions(name="Missouri", country='USA')
        pr26 = ParentRegions(name="Montana", country='USA')
        pr27 = ParentRegions(name="Nebraska", country='USA')
        pr28 = ParentRegions(name="Nevada", country='USA')
        pr29 = ParentRegions(name="New Hampshire", country='USA')
        pr30 = ParentRegions(name="New Jersey", country='USA')
        pr31 = ParentRegions(name="New Mexico", country='USA')
        pr32 = ParentRegions(name="New York", country='USA')
        pr33 = ParentRegions(name="North Carolina", country='USA')
        pr34 = ParentRegions(name="North Dakota", country='USA')
        pr35 = ParentRegions(name="Ohio", country='USA')
        pr36 = ParentRegions(name="Oklahoma", country='USA')
        pr37 = ParentRegions(name="Oregon", country='USA')
        pr38 = ParentRegions(name="Pennsylvania", country='USA')
        pr39 = ParentRegions(name="Rhode Island", country='USA')
        pr40 = ParentRegions(name="South Carolina", country='USA')
        pr41 = ParentRegions(name="South Dakota", country='USA')
        pr42 = ParentRegions(name="Tennessee", country='USA')
        pr43 = ParentRegions(name="Texas", country='USA')
        pr44 = ParentRegions(name="Utah", country='USA')
        pr45 = ParentRegions(name="Vermont", country='USA')
        pr46 = ParentRegions(name="Virginia", country='USA')
        pr47 = ParentRegions(name="Washington", country='USA')
        pr48 = ParentRegions(name="West Virginia", country='USA')
        pr49 = ParentRegions(name="Wisconsin", country='USA')
        pr50 = ParentRegions(name="Wyoming", country='USA')
        

        sr1 = SubRegions(name="Napa Valley", climate="Mediterranean")
        sr2 = SubRegions(name="Finger Lakes", climate="Continental")
        sr3 = SubRegions(name="Willamette Valley", climate="Maritime")
        sr4 = SubRegions(name="Sonoma County", climate="Mediterranean")
        sr5 = SubRegions(name="Monticello", climate="Subtropical/Maritime")
        sr6 = SubRegions(name="Central Coast", climate="Mediterranean")
        sr7 = SubRegions(name="Wahluke Slope", climate="Dry & Warm")
        sr8 = SubRegions(name="Sonoma Valley", climate="Mediterranean")
        sr9 = SubRegions(name="Los Carneros", climate="Mediterranean")
        sr10 = SubRegions(name="Dundee Hills", climate="Maritime")
        sr11 = SubRegions(name="Santa Cruz Mountains", climate="Mediterranean")
        sr12 = SubRegions(name="Fennville", climate="Continental")
        sr13 = SubRegions(name="Guenoc Valley", climate="Continental")
        sr14 = SubRegions(name="San Pasqual Valley", climate="Mediterranean")
        sr15 = SubRegions(name="Santa Maria Valley", climate="Maritime")
        sr16 = SubRegions(name="Chalone", climate="Continental")
        sr17 = SubRegions(name="Lime Kiln Valley", climate="Mediterranean")
        sr18 = SubRegions(name="Augusta", climate="Continental")
        sr19 = SubRegions(name="Cole Ranch", climate="Mediterranean")
        sr20 = SubRegions(name="McDowell Valley", climate="Continental")
        sr21 = SubRegions(name="Suisun Valley", climate="Continental")
        sr22 = SubRegions(name="California Shenandoah Valley", climate="Continental")
        sr23 = SubRegions(name="Cienega Valley", climate="Continental")
        sr24 = SubRegions(name="Paicines", climate="Mediterranean")
        sr25 = SubRegions(name="Rocky Knob", climate="Continental")
        sr26 = SubRegions(name="Lancaster Valley", climate="Continental")
        sr27 = SubRegions(name="Edna Valley", climate="Mediterranean")
        sr28 = SubRegions(name="Isle St. George", climate="Continental")
        sr29 = SubRegions(name="Green Valley of Russian River Valley", climate="Mediterranean")
        sr30 = SubRegions(name="Central Delaware Valley", climate="Continental")
        sr31 = SubRegions(name="Bell Mountain", climate="Continental")
        sr32 = SubRegions(name="San Lucas", climate="Mediterranean")
        sr33 = SubRegions(name="Hudson River Region", climate="Continental")
        sr34 = SubRegions(name="Temecula Valley", climate="Mediterranean")
        sr35 = SubRegions(name="Chalk Hill", climate="Mediterranean")
        sr36 = SubRegions(name="Santa Ynez Valley", climate="Mediterranean")
        sr37 = SubRegions(name="Alexander Valley", climate="Mediterranean")
        sr38 = SubRegions(name="Solano County Green Valley", climate="Mediterranean")
        sr39 = SubRegions(name="Merritt Island", climate="Subtropical/Maritime")
        sr40 = SubRegions(name="El Dorado", climate="Continental")
        sr41 = SubRegions(name="Loramie Creek", climate="Continental")
        sr42 = SubRegions(name="Carmel Valley", climate="Mediterranean")
        sr43 = SubRegions(name="North Fork of Roanoke", climate="Continental")
        sr44 = SubRegions(name="Catoctin", climate="Continental")
        sr45 = SubRegions(name="Linganore", climate="Continental")
        sr46 = SubRegions(name="Shenandoah Valley", climate="Continental")
        sr47 = SubRegions(name="Altus", climate="Continental")
        sr48 = SubRegions(name="Knights Valley", climate="Continental")
        sr49 = SubRegions(name="Northern Sonoma", climate="Mediterranean")
        sr50 = SubRegions(name="Hermann", climate="Continental")
        sr51 = SubRegions(name="Lake Michigan Shore", climate="Continental")
        sr52 = SubRegions(name="Ohio River Valley", climate="Continental")
        sr53 = SubRegions(name="York Mountain", climate="Mediterranean")
        sr54 = SubRegions(name="Fiddletown", climate="Continental")
        sr55 = SubRegions(name="Potter Valley", climate="Continental")
        sr56 = SubRegions(name="Paso Robles", climate="Mediterranean")
        sr57 = SubRegions(name="Anderson Valley", climate="Mediterranean")
        sr58 = SubRegions(name="Pacheco Pass", climate="Mediterranean")
        sr59 = SubRegions(name="Columbia Valley", climate="Continental")
        sr60 = SubRegions(name="Walla Walla Valley", climate="Continental")
        sr61 = SubRegions(name="Lake Erie", climate="Continental")
        sr62 = SubRegions(name="Willow Creek", climate="Continental")
        sr63 = SubRegions(name="Sonoma Mountain", climate="Mediterranean")
        sr64 = SubRegions(name="Southeastern New England", climate="Continental")
        sr65 = SubRegions(name="Madera", climate="Continental")
        sr66 = SubRegions(name="Howell Mountain", climate="Mediterranean")
        sr67 = SubRegions(name="Sonoita", climate="Continental")
        sr68 = SubRegions(name="Monterey", climate="Mediterranean")
        sr69 = SubRegions(name="Mesilla Valley", climate="Continental")
        sr70 = SubRegions(name="Mendocino", climate="Mediterranean")
        sr71 = SubRegions(name="Mississippi Delta", climate="Subtropical/Maritime")
        sr72 = SubRegions(name="Grand River Valley", climate="Continental")
        sr73 = SubRegions(name="Umpqua Valley", climate="Maritime")
        sr74 = SubRegions(name="Northern Neck George Washington Birthplace", climate="Continental")
        sr75 = SubRegions(name="Lodi", climate="Continental")
        sr76 = SubRegions(name="South Coast", climate="Mediterranean")
        sr77 = SubRegions(name="Kanawha River Valley", climate="Continental")
        sr78 = SubRegions(name="Arkansas Mountain", climate="Continental")
        sr79 = SubRegions(name="Mimbres Valley", climate="Continental")
        sr80 = SubRegions(name="Cumberland Valley", climate="Continental")
        sr81 = SubRegions(name="North Yuba", climate="Continental")
        sr82 = SubRegions(name="Old Mission Peninsula", climate="Continental")
        sr83 = SubRegions(name="Stags Leap District", climate="Mediterranean")
        sr84 = SubRegions(name="Ben Lomond Mountain", climate="Continental")
        sr85 = SubRegions(name="Western Connecticut Highlands", climate="Continental")
        sr86 = SubRegions(name="San Benito", climate="Continental")
        sr87 = SubRegions(name="Warren Hills", climate="Continental")
        sr88 = SubRegions(name="Ozark Highlands", climate="Continental")
        sr89 = SubRegions(name="Wild Horse Valley", climate="Continental")
        sr90 = SubRegions(name="Sonoma Coast", climate="Mediterranean")
        sr91 = SubRegions(name="Sierra Foothills", climate="Mediterranean")
        sr92 = SubRegions(name="Mt. Veeder", climate="Mediterranean")
        sr93 = SubRegions(name="Cayuga Lake", climate="Continental")
        sr94 = SubRegions(name="Mt. Harlan", climate="Continental")
        sr95 = SubRegions(name="Rogue Valley", climate="Continental")
        sr96 = SubRegions(name="Santa Clara Valley", climate="Mediterranean")
        sr97 = SubRegions(name="San Ysidro District", climate="Mediterranean")
        sr98 = SubRegions(name="Arroyo Grande Valley", climate="Mediterranean")
        sr99 = SubRegions(name="Virginia's Eastern Shore", climate="Continental")
        sr100 = SubRegions(name="Oakville", climate="Mediterranean")
        sr101 = SubRegions(name="Rutherford", climate="Mediterranean")
        sr102 = SubRegions(name="Texas Hill Country", climate="Continental")
        sr103 = SubRegions(name="Grand Valley", climate="Continental")
        sr104 = SubRegions(name="Dunnigan Hills", climate="Mediterranean")
        sr105 = SubRegions(name="Lake Wisconsin", climate="Continental")
        sr106 = SubRegions(name="Santa Lucia Highlands", climate="Mediterranean")
        sr107 = SubRegions(name="Bennett Valley", climate="Mediterranean")
        sr108 = SubRegions(name="Texas High Plains", climate="Continental")
        sr109 = SubRegions(name="Seiad Valley", climate="Continental")
        sr110 = SubRegions(name="Chiles Valley", climate="Mediterranean")
        sr111 = SubRegions(name="Malibu-Newton Canyon", climate="Mediterranean")
        sr112 = SubRegions(name="Cucamonga Valley", climate="Mediterranean")
        sr113 = SubRegions(name="Redwood Valley", climate="Continental")
        sr114 = SubRegions(name="Hames Valley", climate="Mediterranean")
        sr115 = SubRegions(name="St. Helena", climate="Mediterranean")
        sr116 = SubRegions(name="Texas Davis Mountains", climate="Continental")
        sr117 = SubRegions(name="Diablo Grande", climate="Continental")
        sr118 = SubRegions(name="San Francisco Bay", climate="Mediterranean")
        sr119 = SubRegions(name="The Rocks District of Milton-Freewater", climate="Continental")
        sr120 = SubRegions(name="Diamond Mountain District", climate="Mediterranean")
        sr121 = SubRegions(name="Mendocino Ridge (Outline)", climate="Mediterranean")
        sr122 = SubRegions(name="Yorkville Highlands", climate="Continental")
        sr123 = SubRegions(name="Applegate Valley", climate="Continental")
        sr124 = SubRegions(name="Red Mountain", climate="Continental")
        sr125 = SubRegions(name="Oak Knoll District of Napa Valley", climate="Mediterranean")
        sr126 = SubRegions(name="Yountville", climate="Mediterranean")
        sr127 = SubRegions(name="West Elks", climate="Continental")
        sr128 = SubRegions(name="River Junction", climate="Continental")
        sr129 = SubRegions(name="Rockpile", climate="Continental")
        sr130 = SubRegions(name="Fair Play", climate="Continental")
        sr131 = SubRegions(name="San Bernabe", climate="Mediterranean")
        sr132 = SubRegions(name="Long Island", climate="Maritime")
        sr133 = SubRegions(name="Red Hills Lake County", climate="Continental")
        sr134 = SubRegions(name="Puget Sound", climate="Maritime")
        sr135 = SubRegions(name="Appalachian High Country", climate="Continental")
        sr136 = SubRegions(name="Tip of the Mitt", climate="Continental")
        sr137 = SubRegions(name="Champlain Valley of New York", climate="Continental")
        sr138 = SubRegions(name="Willcox", climate="Continental")
        sr139 = SubRegions(name="Lamorinda", climate="Mediterranean")
        sr140 = SubRegions(name="Lewis-Clark Valley", climate="Continental")
        sr141 = SubRegions(name="Los Olivos District", climate="Mediterranean")
        sr142 = SubRegions(name="Squaw Valley-Miramonte", climate="Continental")
        sr143 = SubRegions(name="Fountaingrove District", climate="Mediterranean")
        sr144 = SubRegions(name="Eagle Foothills", climate="Continental")
        sr145 = SubRegions(name="Santa Margarita Ranch", climate="Mediterranean")
        sr146 = SubRegions(name="Templeton Gap District", climate="Mediterranean")
        sr147 = SubRegions(name="Loess Hills District", climate="Continental")
        sr148 = SubRegions(name="San Miguel District", climate="Mediterranean")
        sr149 = SubRegions(name="San Juan Creek", climate="Mediterranean")
        sr150 = SubRegions(name="Paso Robles Willow Creek District", climate="Mediterranean")
        sr151 = SubRegions(name="Paso Robles Highlands District", climate="Mediterranean")
        sr152 = SubRegions(name="Paso Robles Geneseo District", climate="Mediterranean")
        sr153 = SubRegions(name="Paso Robles Estrella District", climate="Mediterranean")
        sr154 = SubRegions(name="El Pomar District", climate="Mediterranean")
        sr155 = SubRegions(name="Creston District", climate="Mediterranean")
        sr156 = SubRegions(name="Adelaida District", climate="Mediterranean")
        sr157 = SubRegions(name="Eagle Peak Mendocino County", climate="Mediterranean")
        sr158 = SubRegions(name="Manton Valley", climate="Continental")
        sr159 = SubRegions(name="Upper Hiwassee Highlands", climate="Continental")
        sr160 = SubRegions(name="Kelsey Bench-Lake County", climate="Continental")
        sr161 = SubRegions(name="Big Valley District-Lake County", climate="Continental")
        sr162 = SubRegions(name="Ballard Canyon", climate="Mediterranean")
        sr163 = SubRegions(name="Elkton Oregon", climate="Maritime")
        sr164 = SubRegions(name="Indiana Uplands", climate="Continental")
        sr165 = SubRegions(name="Lehigh Valley", climate="Continental")
        sr166 = SubRegions(name="Niagara Escarpment", climate="Continental")
        sr167 = SubRegions(name="Shawnee Hills", climate="Continental")
        sr168 = SubRegions(name="Alexandria Lakes", climate="Continental")
        sr169 = SubRegions(name="Ramona Valley", climate="Mediterranean")
        sr170 = SubRegions(name="Leona Valley", climate="Mediterranean")
        sr171 = SubRegions(name="Happy Canyon of Santa Barbara", climate="Mediterranean")
        sr172 = SubRegions(name="San Antonio Valley", climate="Mediterranean")
        sr173 = SubRegions(name="Tracy Hills", climate="Continental")
        sr174 = SubRegions(name="Cosumnes River", climate="Continental")
        sr175 = SubRegions(name="Mokelumne River", climate="Continental")
        sr176 = SubRegions(name="Jahant", climate="Continental")
        sr177 = SubRegions(name="Clements Hills", climate="Continental")
        sr178 = SubRegions(name="Capay Valley", climate="Mediterranean")
        sr179 = SubRegions(name="Pine Mountain-Cloverdale Peak", climate="Mediterranean")
        sr180 = SubRegions(name="Calistoga", climate="Mediterranean")
        sr181 = SubRegions(name="Moon Mountain District Sonoma County", climate="Mediterranean")
        sr182 = SubRegions(name="Coombsville", climate="Mediterranean")
        sr183 = SubRegions(name="Dos Rios", climate="Continental")
        sr184 = SubRegions(name="Covelo", climate="Continental")
        sr185 = SubRegions(name="Trinity Lakes", climate="Continental")
        sr186 = SubRegions(name="Red Hill Douglas County, Oregon", climate="Continental")
        sr187 = SubRegions(name="Ribbon Ridge", climate="Continental")
        sr188 = SubRegions(name="McMinnville", climate="Continental")
        sr189 = SubRegions(name="Columbia Gorge", climate="Continental")
        sr190 = SubRegions(name="Wahluke Slope", climate="Continental")
        sr191 = SubRegions(name="Snipes Mountain", climate="Continental")
        sr192 = SubRegions(name="Rattlesnake Hills", climate="Continental")
        sr193 = SubRegions(name="Horse Heaven Hills", climate="Continental")
        sr194 = SubRegions(name="Middleburg Virginia", climate="Continental")
        sr195 = SubRegions(name="Haw River Valley", climate="Continental")
        sr196 = SubRegions(name="Wisconsin Ledge", climate="Continental")
        sr197 = SubRegions(name="Upper Mississippi River Valley", climate="Continental")
        sr198 = SubRegions(name="Snake River Valley", climate="Continental")
        sr199 = SubRegions(name="Ancient Lakes of Columbia Valley", climate="Continental")
        sr200 = SubRegions(name="Lake Chelan", climate="Continental")
        sr201 = SubRegions(name="Naches Heights", climate="Continental")
        sr202 = SubRegions(name="Alta Mesa", climate="Mediterranean")
        sr203 = SubRegions(name="Borden Ranch", climate="Continental")
        sr204 = SubRegions(name="Sloughhouse", climate="Continental")
        sr205 = SubRegions(name="Saddle Rock-Malibu", climate="Mediterranean")
        sr206 = SubRegions(name="Sierra Pelona Valley", climate="Continental")
        sr207 = SubRegions(name="Yamhill-Carlton", climate="Maritime")
        sr208 = SubRegions(name="Chehalem Mountains", climate="Maritime")
        sr209 = SubRegions(name="Fort Ross-Seaview", climate="Maritime")
        sr210 = SubRegions(name="Petaluma Gap", climate="Maritime")
        sr211 = SubRegions(name="Monticello", climate="Subtropical/Maritime")
        sr212 = SubRegions(name="Upper Hudson", climate="Continental")
        sr213 = SubRegions(name="Cape May Peninsula", climate="Continental")
        sr214 = SubRegions(name="Dahlonega Plateau", climate="Continental")
        sr215 = SubRegions(name="Eastern Connecticut Highlands", climate="Continental")
        sr216 = SubRegions(name="Crest of the Blue Ridge Henderson County", climate="Continental")
        sr217 = SubRegions(name="Candy Mountain", climate="Continental")
        sr218 = SubRegions(name="Yakima Valley", climate="Continental")
        sr219 = SubRegions(name="Laurelwood District", climate="Continental")
        sr220 = SubRegions(name="Tualatin Hills", climate="Continental")
        sr221 = SubRegions(name="Royal Slope", climate="Continental")
        sr222 = SubRegions(name="Alisos Canyon", climate="Mediterranean")
        sr223 = SubRegions(name="Mt. Pisgah Polk County Oregon", climate="Continental")
        sr224 = SubRegions(name="The Burn of Columbia Valley", climate="Continental")
        sr225 = SubRegions(name="White Bluffs", climate="Continental")
        sr226 = SubRegions(name="Lower Long Tom", climate="Continental")
        sr227 = SubRegions(name="Arroyo Seco", climate="Continental")
        sr228 = SubRegions(name="Upper Lake Valley", climate="Continental")
        sr229 = SubRegions(name="Ulupalakua", climate="Mediterranean")
        sr230 = SubRegions(name="Goose Gap", climate="Continental")
        sr231 = SubRegions(name="Clarksburg", climate="Continental")
        sr232 = SubRegions(name="Virginia Peninsula", climate="Continental")
        sr233 = SubRegions(name="Verde Valley", climate="Continental")
        sr234 = SubRegions(name="Palos Verdes Peninsula", climate="Mediterranean")
        sr235 = SubRegions(name="Gabilan Mountains", climate="Mediterranean")
        sr236 = SubRegions(name="Tehachapi Mountains", climate="Continental")
        sr237 = SubRegions(name="West Sonoma Coast", climate="Mediterranean")
        sr238 = SubRegions(name="Rocky Reach", climate="Continental")
        sr239 = SubRegions(name="Paulsell Valley", climate="Continental")
        sr240 = SubRegions(name="Long Valley-Lake County", climate="Continental")
        sr241 = SubRegions(name="North Coast", climate="Maritime")
        sr242 = SubRegions(name="Clear Lake", climate="Continental")
        sr243 = SubRegions(name="Winters Highlands", climate="Continental")
        sr244 = SubRegions(name="Dry Creek Valley", climate="Mediterranean")
        sr245 = SubRegions(name="Ozark Mountain", climate="Continental")
        sr246 = SubRegions(name="Leelanau Peninsula", climate="Continental")
        sr247 = SubRegions(name="Livermore Valley", climate="Mediterranean")
        sr248 = SubRegions(name="Russian River Valley", climate="Mediterranean")
        sr249 = SubRegions(name="Martha's Vineyard", climate="Maritime")
        sr250 = SubRegions(name="The Hamptons, Long Island", climate="Maritime")
        sr251 = SubRegions(name="North Fork of Long Island", climate="Maritime")
        sr252 = SubRegions(name="Middle Rio Grande Valley", climate="Continental")
        sr253 = SubRegions(name="Fredericksburg in the Texas Hill Country", climate="Continental")
        sr254 = SubRegions(name="Seneca Lake", climate="Continental")
        sr255 = SubRegions(name="Texoma", climate="Continental")
        sr256 = SubRegions(name="Salado Creek", climate="Continental")
        sr257 = SubRegions(name="Sta. Rita Hills", climate="Mediterranean")
        sr258 = SubRegions(name="Mendocino Ridge", climate="Maritime")
        sr259 = SubRegions(name="Malibu Coast", climate="Mediterranean")
        sr260 = SubRegions(name="Outer Coastal Plain", climate="Continental")
        sr261 = SubRegions(name="Yadkin Valley", climate="Continental")
        sr262 = SubRegions(name="Swan Creek", climate="Continental")
        sr263 = SubRegions(name="Inwood Valley", climate="Continental")
        sr264 = SubRegions(name="Antelope Valley of the California High Desert", climate="Continental")
        sr265 = SubRegions(name="Eola-Amity Hills", climate="Continental")
        sr266 = SubRegions(name="Southern Oregon", climate="Continental")
        sr267 = SubRegions(name="Van Duzer Corridor", climate="Maritime")
        sr268 = SubRegions(name="SLO Coast", climate="Maritime")
        sr269 = SubRegions(name="High Valley", climate="Continental")
        

        g1.subregions.extend([sr1, sr4, sr6])
        g2.subregions.extend([sr1, sr2, sr3, sr4, sr5, sr6, sr7])
        g3.subregions.append(sr2)
        g4.subregions.extend([sr1, sr2, sr3, sr4, sr6, sr7])
        g5.subregions.extend([sr1, sr6, sr5]) 
        g6.subregions.extend([sr2, sr7])

        # Associate SubRegions with ParentRegions
        sr1.parent_regions = pr1
        sr2.parent_regions = pr3
        sr3.parent_regions = pr2
        sr4.parent_regions = pr1
        sr5.parent_regions = pr4
        sr6.parent_regions = pr1
        sr7.parent_regions = pr5
        sr8.parent_regions = pr6
        sr9.parent_regions = pr7
      

        u1 = User(first_name='Drew', last_name='Hairston', username='dch528', password='771532Drew!',
                  email_address='dch528@gmail.com', admin=True)

        u2 = User(first_name='John', last_name='Doe', username='tester', password='test123!',
                  email_address='test@test.com', admin=False)

        db.session.add_all([g1, g2, g3, g4, g5, g6, pr1, pr2, pr3, pr4, pr5, sr1, sr2, sr3, sr4, sr5, sr6, sr7, u1, u2])
        db.session.commit()