from models import db, Grapes, ParentRegions, SubRegions, User, grapes_subregions, parentregion_subregions
from app import app

if __name__ == '__main__':
    with app.app_context():
        print("Building Database...")

   

        # Clear existing data
        db.session.query(grapes_subregions).delete()
        db.session.query(parentregion_subregions).delete()
        db.session.query(Grapes).delete()
        db.session.query(ParentRegions).delete()
        db.session.query(SubRegions).delete()
        db.session.query(User).delete()

        db.create_all()
        g1 = Grapes(name="Cabernet Sauvignon", color='Red', image='../public/cabernetsauvignon.jpg')
        g2 = Grapes(name="Chardonnay", color='White', image='../public/chardonnay.jpeg')
        g3 = Grapes(name="Riesling", color='White', image='../public/Riesling.jpg')
        g4 = Grapes(name="Pinot Noir", color='Red', image='../public/pinotnoir.jpg')
        g5 = Grapes(name="Sauvignon Blanc", color='White', image='../public/sauvignon-blanc.jpg')
        g6 = Grapes(name="Rkatsiteli", color='White', image='../public/Rkatsiteli.jpg')
        g7 = Grapes(name="Nebbiolo", color='Red', image='../public/nebbiolo.jpg')
        g8 = Grapes(name='Syrah', color='Red', image='../public/Syrah.jpg')
        g9 = Grapes(name='Pinot Grigio', color='White', image='../public/Pinot_Grigio.jpg')
        g10 = Grapes(name='Grenache', color='Red', image='../public/Grenachejpg.jpg')
        g11 = Grapes(name='Muscat', color='White', image='../public/muscat.jpg')
        g12 = Grapes(name='Saperavi', color='Red', image='../public/Saperavi.jpg')
        g13 = Grapes(name='Cabernet Franc', color='Red', image='../public/cabernetfranc.jpg')
        g14 = Grapes(name='Sangiovese', color='Red', image='../public/sangiovese.jpg')
        g15 = Grapes(name='Semillon', color='White', image='../public/semillon.jpg')
        g16 = Grapes(name='Pinot Blanc', color='Red', image='../public/pinotblanc.jpg')
        g17 = Grapes(name='Zinfandel', color='Red', image='../public/Zinfandel.jpg')
        g18 = Grapes(name='Merlot', color='Red', image='../public/merlot.jpg')
        g19 = Grapes(name='Colombard', color='White', image='../public/Colombard.jpg')
        g20 = Grapes(name='Chenin Blanc', color='Red', image='../public/Chenin.jpg')
        g21 = Grapes(name='Alicante Bouschet', color='Red', image='../public/alicante-bouschet.jpg')
        g22 = Grapes(name='Agiortiko', color='Red', image='../public/agiorgitiko.jpg')
        g23 = Grapes(name='Malbec', color='Red', image='../public/Malbec.jpg')
        g24 = Grapes(name='Barbera', color='Red', image='../public/Barbera.jpg')
        g25 = Grapes(name='Dolcetto', color='Red', image='../public/Dolcetto.jpg')
        g26 = Grapes(name='Blaufränkisch', color='Red', image='../public/blaufrankisch.jpeg')
        g27 = Grapes(name='Carménère', color='Red', image='../public/carmenere.jpg')
        g28 = Grapes(name='Grüner Veltliner', color='White', image='../public/gruner.jpeg')
        g29 = Grapes(name='Montepulciano', color='Red', image='../public/Montepulciano.jpg')
        g30 = Grapes(name='Mourvèdre', color='Red', image='../public/mourvedre.jpg')
        g31 = Grapes(name='Nero d\'Avola', color='Red', image='../public/nerodavola.jpg')
        g32 = Grapes(name='Petite Syrah', color='Red', image='../public/petitsyrah.jpg')
        g33 = Grapes(name='Tempranillo', color='Red', image='../public/tempranillo.jpg')
        g34 = Grapes(name='Marselan', color='Red', image='../public/marselan.jpg')
        g35 = Grapes(name='Carignan', color='Red', image='../public/carignan.jpg')
        g36 = Grapes(name='Albariño', color='White', image='../public/albarinho.jpg')
        g37 = Grapes(name='Furmint', color='White', image='../public/Furmint.jpg')
        g38 = Grapes(name='Cortese', color='White', image='../public/cortese.jpg')
        g39 = Grapes(name='Glera', color='White', image='../public/glera.jpg')
        g40 = Grapes(name='Charbono', color='Red', image='../public/charbono.jpg')
        g41 = Grapes(name='Marsanne', color='White', image='../public/marsanne.jpg')
        g42 = Grapes(name='Roussanne', color='White', image='../public/Roussanne.jpg')
        g43 = Grapes(name='Petit Manseng', color='White', image='../public/petitmanseng.jpg')
        g44 = Grapes(name='Verdejo', color='White', image='../public/verdejo.jpg')
        g45 = Grapes(name='Lambrusco', color='Red', image='../public/lambrusco.jpg')
        g46 = Grapes(name='Gamay', color='Red', image='../public/gamay.jpg')
        g47 = Grapes(name='Xinomavro', color='Red', image='../public/xinomavro.jpg')
        g48 = Grapes(name='Xarelo-lo', color='White', image='../public/xarello.jpg')
        g49 = Grapes(name='Macabeo', color='White', image='../public/macabeo.jpg')
        g50 = Grapes(name='Parellada', color='White', image='../public/parellada.jpg')
        g51 = Grapes(name='Hondarrabi Zuri', color='White', image='../public/hondarribi-zuri.jpg')
        g52 = Grapes(name='Hondarrabi Beltza', color='Red', image='../public/beltza.jpg')
        g53 = Grapes(name='Muscadet', color='White', image='../public/muscadet.jpg')
        g54 = Grapes(name='Kisi', color='White', image='../public/kisi.jpg')
        g55 = Grapes(name='Tsoulikouri', color='White', image='../public/tsoulikouri.jpg')
        g56 = Grapes(name='Aladasturi', color='Red', image='../public/aladasturi.jpg')
        g57 = Grapes(name='Dzelshavi', color='Red', image='../public/dzelshavi.jpg')
        g58 = Grapes(name='Tsitska', color='White', image='../public/tsitska.jpg')
        g59 = Grapes(name='Krakhuna', color='White', image='../public/krakhuna.jpg')
        g60 = Grapes(name='Chinuri', color='White', image='../public/chinuri.jpg')




        pr1 = ParentRegions(name = "Alabama", abbreviation = "AL", country = "USA")
        pr2 = ParentRegions(name = "Alaska", abbreviation = "AK", country = "USA" )
        pr3 = ParentRegions(name = "Arizona", abbreviation = "AZ", country = "USA" )
        pr4 = ParentRegions(name = "Arkansas", abbreviation = "AR", country = "USA")
        pr5 = ParentRegions(name = "California", abbreviation = "CA", country = "USA")
        pr6 = ParentRegions(name = "Colorado", abbreviation = "CO", country = "USA")
        pr7 = ParentRegions(name = "Connecticut", abbreviation = "CT", country = "USA")
        pr8 = ParentRegions(name = "Delaware", abbreviation = "DE", country = "USA")
        pr9 = ParentRegions(name = "Florida", abbreviation = "FL", country = "USA")
        pr10 = ParentRegions(name = "Georgia", abbreviation = "GA", country = "USA")
        pr11 = ParentRegions(name = "Hawaii", abbreviation = "HI", country = "USA")
        pr12 = ParentRegions(name = "Idaho", abbreviation = "ID", country = "USA")
        pr13 = ParentRegions(name = "Illinois", abbreviation = "IL", country = "USA")
        pr14 = ParentRegions(name = "Indiana", abbreviation = "IN", country = "USA")
        pr15 = ParentRegions(name = "Iowa", abbreviation = "IA", country = "USA")
        pr16 = ParentRegions(name = "Kansas", abbreviation = "KS", country = "USA")
        pr17 = ParentRegions(name = "Kentucky", abbreviation = "KY", country = "USA")
        pr18 = ParentRegions(name = "Louisiana", abbreviation = "LA", country = "USA")
        pr19 = ParentRegions(name = "Maine", abbreviation = "ME", country = "USA")
        pr20 = ParentRegions(name = "Maryland", abbreviation = "MD", country = "USA")
        pr21 = ParentRegions(name = "Massachusetts", abbreviation = "MA", country = "USA")
        pr22 = ParentRegions(name = "Michigan", abbreviation = "MI", country = "USA")
        pr23 = ParentRegions(name = "Minnesota", abbreviation = "MN", country = "USA")
        pr24 = ParentRegions(name = "Mississippi", abbreviation = "MS", country = "USA")
        pr25 = ParentRegions(name = "Missouri", abbreviation = "MO", country = "USA")
        pr26 = ParentRegions(name = "Montana", abbreviation = "MT", country = "USA")
        pr27 = ParentRegions(name = "Nebraska", abbreviation = "NE", country = "USA")
        pr28 = ParentRegions(name = "Nevada", abbreviation = "NV", country = "USA")
        pr29 = ParentRegions(name = "New Hampshire", abbreviation = "NH", country = "USA")
        pr30 = ParentRegions(name = "New Jersey", abbreviation = "NJ", country = "USA")
        pr31 = ParentRegions(name = "New Mexico", abbreviation = "NM", country = "USA")
        pr32 = ParentRegions(name = "New York", abbreviation = "NY", country = "USA")
        pr33 = ParentRegions(name = "North Carolina", abbreviation = "NC", country = "USA")
        pr34 = ParentRegions(name = "North Dakota", abbreviation = "ND", country = "USA")
        pr35 = ParentRegions(name = "Ohio", abbreviation = "OH", country = "USA")
        pr36 = ParentRegions(name = "Oklahoma", abbreviation = "OK", country = "USA")
        pr37 = ParentRegions(name = "Oregon", abbreviation = "OR", country = "USA")
        pr38 = ParentRegions(name = "Pennsylvania", abbreviation = "PA", country = "USA")
        pr39 = ParentRegions(name = "Rhode Island", abbreviation = "RI", country = "USA")
        pr40 = ParentRegions(name = "South Carolina", abbreviation = "SC", country = "USA")
        pr41 = ParentRegions(name = "South Dakota", abbreviation = "SD", country = "USA")
        pr42 = ParentRegions(name = "Tennessee", abbreviation = "TN", country = "USA")
        pr43 = ParentRegions(name = "Texas", abbreviation = "TX", country = "USA")
        pr44 = ParentRegions(name = "Utah", abbreviation = "UT", country = "USA")
        pr45 = ParentRegions(name = "Vermont", abbreviation = "VT", country = "USA")
        pr46 = ParentRegions(name = "Virginia", abbreviation = "VA", country = "USA")
        pr47 = ParentRegions(name = "Washington", abbreviation = "WA", country = "USA")
        pr48 = ParentRegions(name = "West Virginia", abbreviation = "WV", country = "USA")
        pr49 = ParentRegions(name = "Wisconsin", abbreviation = "WI", country = "USA")
        pr50 = ParentRegions(name = "Wyoming", abbreviation = "WY", country = "USA")
        

        sr1 = SubRegions(name="Napa Valley", climate="Mediterranean")
        sr2 = SubRegions(name="Finger Lakes", climate="Continental")
        sr3 = SubRegions(name="Willamette Valley", climate="Maritime")
        sr4 = SubRegions(name="Sonoma County", climate="Mediterranean")
        sr5 = SubRegions(name="Monticello", climate="Subtropical/Maritime")
        sr6 = SubRegions(name="Central Coast", climate="Mediterranean")
        sr7 = SubRegions(name="Wahluke Slope", climate="Dry & Warm")
        sr8 = SubRegions(name="Sonoma Valley", climate="Mediterranean")
        sr9 = SubRegions(name="Los Carneros", climate="Mediterranean")
        sr10 = SubRegions(name="Dundee Hills", climate="Maritime")
        sr11 = SubRegions(name="Santa Cruz Mountains", climate="Mediterranean")
        sr12 = SubRegions(name="Fennville", climate="Continental")
        sr13 = SubRegions(name="Guenoc Valley", climate="Continental")
        sr14 = SubRegions(name="San Pasqual Valley", climate="Mediterranean")
        sr15 = SubRegions(name="Santa Maria Valley", climate="Maritime")
        sr16 = SubRegions(name="Chalone", climate="Continental")
        sr17 = SubRegions(name="Lime Kiln Valley", climate="Mediterranean")
        sr18 = SubRegions(name="Augusta", climate="Continental")
        sr19 = SubRegions(name="Cole Ranch", climate="Mediterranean")
        sr20 = SubRegions(name="McDowell Valley", climate="Continental")
        sr21 = SubRegions(name="Suisun Valley", climate="Continental")
        sr22 = SubRegions(name="California Shenandoah Valley", climate="Continental")
        sr23 = SubRegions(name="Cienega Valley", climate="Continental")
        sr24 = SubRegions(name="Paicines", climate="Mediterranean")
        sr25 = SubRegions(name="Rocky Knob", climate="Continental")
        sr26 = SubRegions(name="Lancaster Valley", climate="Continental")
        sr27 = SubRegions(name="Edna Valley", climate="Mediterranean")
        sr28 = SubRegions(name="Isle St. George", climate="Continental")
        sr29 = SubRegions(name="Green Valley of Russian River Valley", climate="Mediterranean")
        sr30 = SubRegions(name="Central Delaware Valley", climate="Continental")
        sr31 = SubRegions(name="Bell Mountain", climate="Continental")
        sr32 = SubRegions(name="San Lucas", climate="Mediterranean")
        sr33 = SubRegions(name="Hudson River Region", climate="Continental")
        sr34 = SubRegions(name="Temecula Valley", climate="Mediterranean")
        sr35 = SubRegions(name="Chalk Hill", climate="Mediterranean")
        sr36 = SubRegions(name="Santa Ynez Valley", climate="Mediterranean")
        sr37 = SubRegions(name="Alexander Valley", climate="Mediterranean")
        sr38 = SubRegions(name="Solano County Green Valley", climate="Mediterranean")
        sr39 = SubRegions(name="Merritt Island", climate="Subtropical/Maritime")
        sr40 = SubRegions(name="El Dorado", climate="Continental")
        sr41 = SubRegions(name="Loramie Creek", climate="Continental")
        sr42 = SubRegions(name="Carmel Valley", climate="Mediterranean")
        sr43 = SubRegions(name="North Fork of Roanoke", climate="Continental")
        sr44 = SubRegions(name="Catoctin", climate="Continental")
        sr45 = SubRegions(name="Linganore", climate="Continental")
        sr46 = SubRegions(name="Shenandoah Valley", climate="Continental")
        sr47 = SubRegions(name="Altus", climate="Continental")
        sr48 = SubRegions(name="Knights Valley", climate="Continental")
        sr49 = SubRegions(name="Northern Sonoma", climate="Mediterranean")
        sr50 = SubRegions(name="Hermann", climate="Continental")
        sr51 = SubRegions(name="Lake Michigan Shore", climate="Continental")
        sr52 = SubRegions(name="Ohio River Valley", climate="Continental")
        sr53 = SubRegions(name="York Mountain", climate="Mediterranean")
        sr54 = SubRegions(name="Fiddletown", climate="Continental")
        sr55 = SubRegions(name="Potter Valley", climate="Continental")
        sr56 = SubRegions(name="Paso Robles", climate="Mediterranean")
        sr57 = SubRegions(name="Anderson Valley", climate="Mediterranean")
        sr58 = SubRegions(name="Pacheco Pass", climate="Mediterranean")
        sr59 = SubRegions(name="Columbia Valley", climate="Continental")
        sr60 = SubRegions(name="Walla Walla Valley", climate="Continental")
        sr61 = SubRegions(name="Lake Erie", climate="Continental")
        sr62 = SubRegions(name="Willow Creek", climate="Continental")
        sr63 = SubRegions(name="Sonoma Mountain", climate="Mediterranean")
        sr64 = SubRegions(name="Southeastern New England", climate="Continental")
        sr65 = SubRegions(name="Madera", climate="Continental")
        sr66 = SubRegions(name="Howell Mountain", climate="Mediterranean")
        sr67 = SubRegions(name="Sonoita", climate="Continental")
        sr68 = SubRegions(name="Monterey", climate="Mediterranean")
        sr69 = SubRegions(name="Mesilla Valley", climate="Continental")
        sr70 = SubRegions(name="Mendocino", climate="Mediterranean")
        sr71 = SubRegions(name="Mississippi Delta", climate="Subtropical/Maritime")
        sr72 = SubRegions(name="Grand River Valley", climate="Continental")
        sr73 = SubRegions(name="Umpqua Valley", climate="Maritime")
        sr74 = SubRegions(name="Northern Neck George Washington Birthplace", climate="Continental")
        sr75 = SubRegions(name="Lodi", climate="Continental")
        sr76 = SubRegions(name="South Coast", climate="Mediterranean")
        sr77 = SubRegions(name="Kanawha River Valley", climate="Continental")
        sr78 = SubRegions(name="Arkansas Mountain", climate="Continental")
        sr79 = SubRegions(name="Mimbres Valley", climate="Continental")
        sr80 = SubRegions(name="Cumberland Valley", climate="Continental")
        sr81 = SubRegions(name="North Yuba", climate="Continental")
        sr82 = SubRegions(name="Old Mission Peninsula", climate="Continental")
        sr83 = SubRegions(name="Stags Leap District", climate="Mediterranean")
        sr84 = SubRegions(name="Ben Lomond Mountain", climate="Continental")
        sr85 = SubRegions(name="Western Connecticut Highlands", climate="Continental")
        sr86 = SubRegions(name="San Benito", climate="Continental")
        sr87 = SubRegions(name="Warren Hills", climate="Continental")
        sr88 = SubRegions(name="Ozark Highlands", climate="Continental")
        sr89 = SubRegions(name="Wild Horse Valley", climate="Continental")
        sr90 = SubRegions(name="Sonoma Coast", climate="Mediterranean")
        sr91 = SubRegions(name="Sierra Foothills", climate="Mediterranean")
        sr92 = SubRegions(name="Mt. Veeder", climate="Mediterranean")
        sr93 = SubRegions(name="Cayuga Lake", climate="Continental")
        sr94 = SubRegions(name="Mt. Harlan", climate="Continental")
        sr95 = SubRegions(name="Rogue Valley", climate="Continental")
        sr96 = SubRegions(name="Santa Clara Valley", climate="Mediterranean")
        sr97 = SubRegions(name="San Ysidro District", climate="Mediterranean")
        sr98 = SubRegions(name="Arroyo Grande Valley", climate="Mediterranean")
        sr99 = SubRegions(name="Virginia's Eastern Shore", climate="Continental")
        sr100 = SubRegions(name="Oakville", climate="Mediterranean")
        sr101 = SubRegions(name="Rutherford", climate="Mediterranean")
        sr102 = SubRegions(name="Texas Hill Country", climate="Continental")
        sr103 = SubRegions(name="Grand Valley", climate="Continental")
        sr104 = SubRegions(name="Dunnigan Hills", climate="Mediterranean")
        sr105 = SubRegions(name="Lake Wisconsin", climate="Continental")
        sr106 = SubRegions(name="Santa Lucia Highlands", climate="Mediterranean")
        sr107 = SubRegions(name="Bennett Valley", climate="Mediterranean")
        sr108 = SubRegions(name="Texas High Plains", climate="Continental")
        sr109 = SubRegions(name="Seiad Valley", climate="Continental")
        sr110 = SubRegions(name="Chiles Valley", climate="Mediterranean")
        sr111 = SubRegions(name="Malibu-Newton Canyon", climate="Mediterranean")
        sr112 = SubRegions(name="Cucamonga Valley", climate="Mediterranean")
        sr113 = SubRegions(name="Redwood Valley", climate="Continental")
        sr114 = SubRegions(name="Hames Valley", climate="Mediterranean")
        sr115 = SubRegions(name="St. Helena", climate="Mediterranean")
        sr116 = SubRegions(name="Texas Davis Mountains", climate="Continental")
        sr117 = SubRegions(name="Diablo Grande", climate="Continental")
        sr118 = SubRegions(name="San Francisco Bay", climate="Mediterranean")
        sr119 = SubRegions(name="The Rocks District of Milton-Freewater", climate="Continental")
        sr120 = SubRegions(name="Diamond Mountain District", climate="Mediterranean")
        sr121 = SubRegions(name="Mendocino Ridge (Outline)", climate="Mediterranean")
        sr122 = SubRegions(name="Yorkville Highlands", climate="Continental")
        sr123 = SubRegions(name="Applegate Valley", climate="Continental")
        sr124 = SubRegions(name="Red Mountain", climate="Continental")
        sr125 = SubRegions(name="Oak Knoll District of Napa Valley", climate="Mediterranean")
        sr126 = SubRegions(name="Yountville", climate="Mediterranean")
        sr127 = SubRegions(name="West Elks", climate="Continental")
        sr128 = SubRegions(name="River Junction", climate="Continental")
        sr129 = SubRegions(name="Rockpile", climate="Continental")
        sr130 = SubRegions(name="Fair Play", climate="Continental")
        sr131 = SubRegions(name="San Bernabe", climate="Mediterranean")
        sr132 = SubRegions(name="Long Island", climate="Maritime")
        sr133 = SubRegions(name="Red Hills Lake County", climate="Continental")
        sr134 = SubRegions(name="Puget Sound", climate="Maritime")
        sr135 = SubRegions(name="Appalachian High Country", climate="Continental")
        sr136 = SubRegions(name="Tip of the Mitt", climate="Continental")
        sr137 = SubRegions(name="Champlain Valley of New York", climate="Continental")
        sr138 = SubRegions(name="Willcox", climate="Continental")
        sr139 = SubRegions(name="Lamorinda", climate="Mediterranean")
        sr140 = SubRegions(name="Lewis-Clark Valley", climate="Continental")
        sr141 = SubRegions(name="Los Olivos District", climate="Mediterranean")
        sr142 = SubRegions(name="Squaw Valley-Miramonte", climate="Continental")
        sr143 = SubRegions(name="Fountaingrove District", climate="Mediterranean")
        sr144 = SubRegions(name="Eagle Foothills", climate="Continental")
        sr145 = SubRegions(name="Santa Margarita Ranch", climate="Mediterranean")
        sr146 = SubRegions(name="Templeton Gap District", climate="Mediterranean")
        sr147 = SubRegions(name="Loess Hills District", climate="Continental")
        sr148 = SubRegions(name="San Miguel District", climate="Mediterranean")
        sr149 = SubRegions(name="San Juan Creek", climate="Mediterranean")
        sr150 = SubRegions(name="Paso Robles Willow Creek District", climate="Mediterranean")
        sr151 = SubRegions(name="Paso Robles Highlands District", climate="Mediterranean")
        sr152 = SubRegions(name="Paso Robles Geneseo District", climate="Mediterranean")
        sr153 = SubRegions(name="Paso Robles Estrella District", climate="Mediterranean")
        sr154 = SubRegions(name="El Pomar District", climate="Mediterranean")
        sr155 = SubRegions(name="Creston District", climate="Mediterranean")
        sr156 = SubRegions(name="Adelaida District", climate="Mediterranean")
        sr157 = SubRegions(name="Eagle Peak Mendocino County", climate="Mediterranean")
        sr158 = SubRegions(name="Manton Valley", climate="Continental")
        sr159 = SubRegions(name="Upper Hiwassee Highlands", climate="Continental")
        sr160 = SubRegions(name="Kelsey Bench-Lake County", climate="Continental")
        sr161 = SubRegions(name="Big Valley District-Lake County", climate="Continental")
        sr162 = SubRegions(name="Ballard Canyon", climate="Mediterranean")
        sr163 = SubRegions(name="Elkton Oregon", climate="Maritime")
        sr164 = SubRegions(name="Indiana Uplands", climate="Continental")
        sr165 = SubRegions(name="Lehigh Valley", climate="Continental")
        sr166 = SubRegions(name="Niagara Escarpment", climate="Continental")
        sr167 = SubRegions(name="Shawnee Hills", climate="Continental")
        sr168 = SubRegions(name="Alexandria Lakes", climate="Continental")
        sr169 = SubRegions(name="Ramona Valley", climate="Mediterranean")
        sr170 = SubRegions(name="Leona Valley", climate="Mediterranean")
        sr171 = SubRegions(name="Happy Canyon of Santa Barbara", climate="Mediterranean")
        sr172 = SubRegions(name="San Antonio Valley", climate="Mediterranean")
        sr173 = SubRegions(name="Tracy Hills", climate="Continental")
        sr174 = SubRegions(name="Cosumnes River", climate="Continental")
        sr175 = SubRegions(name="Mokelumne River", climate="Continental")
        sr176 = SubRegions(name="Jahant", climate="Continental")
        sr177 = SubRegions(name="Clements Hills", climate="Continental")
        sr178 = SubRegions(name="Capay Valley", climate="Mediterranean")
        sr179 = SubRegions(name="Pine Mountain-Cloverdale Peak", climate="Mediterranean")
        sr180 = SubRegions(name="Calistoga", climate="Mediterranean")
        sr181 = SubRegions(name="Moon Mountain District Sonoma County", climate="Mediterranean")
        sr182 = SubRegions(name="Coombsville", climate="Mediterranean")
        sr183 = SubRegions(name="Dos Rios", climate="Continental")
        sr184 = SubRegions(name="Covelo", climate="Continental")
        sr185 = SubRegions(name="Trinity Lakes", climate="Continental")
        sr186 = SubRegions(name="Red Hill Douglas County, Oregon", climate="Continental")
        sr187 = SubRegions(name="Ribbon Ridge", climate="Continental")
        sr188 = SubRegions(name="McMinnville", climate="Continental")
        sr189 = SubRegions(name="Columbia Gorge", climate="Continental")
    
        sr191 = SubRegions(name="Snipes Mountain", climate="Continental")
        sr192 = SubRegions(name="Rattlesnake Hills", climate="Continental")
        sr193 = SubRegions(name="Horse Heaven Hills", climate="Continental")
        sr194 = SubRegions(name="Middleburg Virginia", climate="Continental")
        sr195 = SubRegions(name="Haw River Valley", climate="Continental")
        sr196 = SubRegions(name="Wisconsin Ledge", climate="Continental")
        sr197 = SubRegions(name="Upper Mississippi River Valley", climate="Continental")
        sr198 = SubRegions(name="Snake River Valley", climate="Continental")
        sr199 = SubRegions(name="Ancient Lakes of Columbia Valley", climate="Continental")
        sr200 = SubRegions(name="Lake Chelan", climate="Continental")
        sr201 = SubRegions(name="Naches Heights", climate="Continental")
        sr202 = SubRegions(name="Alta Mesa", climate="Mediterranean")
        sr203 = SubRegions(name="Borden Ranch", climate="Continental")
        sr204 = SubRegions(name="Sloughhouse", climate="Continental")
        sr205 = SubRegions(name="Saddle Rock-Malibu", climate="Mediterranean")
        sr206 = SubRegions(name="Sierra Pelona Valley", climate="Continental")
        sr207 = SubRegions(name="Yamhill-Carlton", climate="Maritime")
        sr208 = SubRegions(name="Chehalem Mountains", climate="Maritime")
        sr209 = SubRegions(name="Fort Ross-Seaview", climate="Maritime")
        sr210 = SubRegions(name="Petaluma Gap", climate="Maritime")
        sr212 = SubRegions(name="Upper Hudson", climate="Continental")
        sr213 = SubRegions(name="Cape May Peninsula", climate="Continental")
        sr214 = SubRegions(name="Dahlonega Plateau", climate="Continental")
        sr215 = SubRegions(name="Eastern Connecticut Highlands", climate="Continental")
        sr216 = SubRegions(name="Crest of the Blue Ridge Henderson County", climate="Continental")
        sr217 = SubRegions(name="Candy Mountain", climate="Continental")
        sr218 = SubRegions(name="Yakima Valley", climate="Continental")
        sr219 = SubRegions(name="Laurelwood District", climate="Continental")
        sr220 = SubRegions(name="Tualatin Hills", climate="Continental")
        sr221 = SubRegions(name="Royal Slope", climate="Continental")
        sr222 = SubRegions(name="Alisos Canyon", climate="Mediterranean")
        sr223 = SubRegions(name="Mt. Pisgah Polk County Oregon", climate="Continental")
        sr224 = SubRegions(name="The Burn of Columbia Valley", climate="Continental")
        sr225 = SubRegions(name="White Bluffs", climate="Continental")
        sr226 = SubRegions(name="Lower Long Tom", climate="Continental")
        sr227 = SubRegions(name="Arroyo Seco", climate="Continental")
        sr228 = SubRegions(name="Upper Lake Valley", climate="Continental")
        sr229 = SubRegions(name="Ulupalakua", climate="Mediterranean")
        sr230 = SubRegions(name="Goose Gap", climate="Continental")
        sr231 = SubRegions(name="Clarksburg", climate="Continental")
        sr232 = SubRegions(name="Virginia Peninsula", climate="Continental")
        sr233 = SubRegions(name="Verde Valley", climate="Continental")
        sr234 = SubRegions(name="Palos Verdes Peninsula", climate="Mediterranean")
        sr235 = SubRegions(name="Gabilan Mountains", climate="Mediterranean")
        sr236 = SubRegions(name="Tehachapi Mountains", climate="Continental")
        sr237 = SubRegions(name="West Sonoma Coast", climate="Mediterranean")
        sr238 = SubRegions(name="Rocky Reach", climate="Continental")
        sr239 = SubRegions(name="Paulsell Valley", climate="Continental")
        sr240 = SubRegions(name="Long Valley-Lake County", climate="Continental")
        sr241 = SubRegions(name="North Coast", climate="Maritime")
        sr242 = SubRegions(name="Clear Lake", climate="Continental")
        sr243 = SubRegions(name="Winters Highlands", climate="Continental")
        sr244 = SubRegions(name="Dry Creek Valley", climate="Mediterranean")
        sr245 = SubRegions(name="Ozark Mountain", climate="Continental")
        sr246 = SubRegions(name="Leelanau Peninsula", climate="Continental")
        sr247 = SubRegions(name="Livermore Valley", climate="Mediterranean")
        sr248 = SubRegions(name="Russian River Valley", climate="Mediterranean")
        sr249 = SubRegions(name="Martha's Vineyard", climate="Maritime")
        sr250 = SubRegions(name="The Hamptons, Long Island", climate="Maritime")
        sr251 = SubRegions(name="North Fork of Long Island", climate="Maritime")
        sr252 = SubRegions(name="Middle Rio Grande Valley", climate="Continental")
        sr253 = SubRegions(name="Fredericksburg in the Texas Hill Country", climate="Continental")
        sr254 = SubRegions(name="Seneca Lake", climate="Continental")
        sr255 = SubRegions(name="Texoma", climate="Continental")
        sr256 = SubRegions(name="Salado Creek", climate="Continental")
        sr257 = SubRegions(name="Sta. Rita Hills", climate="Mediterranean")
        sr258 = SubRegions(name="Mendocino Ridge", climate="Maritime")
        sr259 = SubRegions(name="Malibu Coast", climate="Mediterranean")
        sr260 = SubRegions(name="Outer Coastal Plain", climate="Continental")
        sr261 = SubRegions(name="Yadkin Valley", climate="Continental")
        sr262 = SubRegions(name="Swan Creek", climate="Continental")
        sr263 = SubRegions(name="Inwood Valley", climate="Continental")
        sr264 = SubRegions(name="Antelope Valley of the California High Desert", climate="Continental")
        sr265 = SubRegions(name="Eola-Amity Hills", climate="Continental")
        sr266 = SubRegions(name="Southern Oregon", climate="Continental")
        sr267 = SubRegions(name="Van Duzer Corridor", climate="Maritime")
        sr268 = SubRegions(name="SLO Coast", climate="Maritime")
        sr269 = SubRegions(name="High Valley", climate="Continental")
        
        sr245.parent_regions.extend([pr4, pr25, pr36])
        sr1.parent_regions.append(pr5)
        sr8.parent_regions.append(pr5)
        sr9.parent_regions.append(pr5)
        sr10.parent_regions.append(pr37)
        sr3.parent_regions.append(pr37)
        sr11.parent_regions.append(pr5)
        sr12.parent_regions.append(pr22)
        sr13.parent_regions.append(pr5)
        sr2.parent_regions.append(pr32)
        sr14.parent_regions.append(pr5)
        sr15.parent_regions.append(pr5)
        sr16.parent_regions.append(pr5)
        sr17.parent_regions.append(pr5)
        sr18.parent_regions.append(pr25)
        sr19.parent_regions.append(pr5)
        sr246.parent_regions.append(pr22)
        sr20.parent_regions.append(pr5)
        sr21.parent_regions.append(pr5)
        sr22.parent_regions.append(pr5)
        sr247.parent_regions.append(pr5)
        sr23.parent_regions.append(pr5)
        sr24.parent_regions.append(pr5)
        sr25.parent_regions.append(pr46)
        sr26.parent_regions.append(pr38)
        sr27.parent_regions.append(pr5)
        sr28.parent_regions.append(pr35)
        sr29.parent_regions.append(pr5)
        sr30.parent_regions.extend([pr30, pr38])
        sr31.parent_regions.append(pr43)
        sr32.parent_regions.append(pr5)
        sr33.parent_regions.append(pr32)
        sr34.parent_regions.append(pr5)
        sr35.parent_regions.append(pr5)
        sr36.parent_regions.append(pr5)
        sr37.parent_regions.append(pr5)
        sr38.parent_regions.append(pr5)
        sr39.parent_regions.append(pr5)
        sr40.parent_regions.append(pr5)
        sr41.parent_regions.append(pr35)
        sr42.parent_regions.append(pr5)
        sr43.parent_regions.append(pr46)
        sr44.parent_regions.append(pr20)
        sr248.parent_regions.append(pr5)
        sr45.parent_regions.append(pr20)
        sr46.parent_regions.append(pr46)
        sr47.parent_regions.append(pr4)
        sr48.parent_regions.append(pr5)
        sr49.parent_regions.append(pr5)
        sr50.parent_regions.append(pr25)
        sr51.parent_regions.append(pr22)
        sr52.parent_regions.extend([pr14, pr17, pr35, pr48])
        sr6.parent_regions.append(pr5)
        sr249.parent_regions.append(pr21)
        sr53.parent_regions.append(pr5)
        sr54.parent_regions.append(pr5)
        sr55.parent_regions.append(pr5)
        sr56.parent_regions.append(pr5)
        sr57.parent_regions.append(pr5)
        sr58.parent_regions.append(pr5)
        sr59.parent_regions.extend([pr37, pr47])
        sr60.parent_regions.extend([pr37, pr47])
        sr61.parent_regions.extend([pr32, pr35, pr38])
        sr62.parent_regions.append(pr5)
        sr63.parent_regions.append(pr5)
        sr64.parent_regions.extend([pr7, pr21, pr39])
        sr65.parent_regions.append(pr5)
        sr66.parent_regions.append(pr5)
        sr67.parent_regions.append(pr3)
        sr250.parent_regions.append(pr32)
        sr68.parent_regions.append(pr5)
        sr69.parent_regions.extend([pr31, pr43])
        sr70.parent_regions.append(pr5)
        sr71.parent_regions.extend([pr18, pr24, pr42])
        sr72.parent_regions.append(pr35)
        sr73.parent_regions.append(pr37)
        sr74.parent_regions.append(pr46)
        sr251.parent_regions.append(pr32)
        sr75.parent_regions.append(pr5)
        sr76.parent_regions.append(pr5)
        sr77.parent_regions.append(pr48)
        sr78.parent_regions.append(pr4)
        sr79.parent_regions.append(pr31)
        sr80.parent_regions.extend([pr20, pr38])
        sr81.parent_regions.append(pr5)
        sr82.parent_regions.append(pr22)
        sr83.parent_regions.append(pr5)
        sr84.parent_regions.append(pr5)
        sr85.parent_regions.append(pr7)
        sr86.parent_regions.append(pr5)
        sr87.parent_regions.append(pr30)
        sr88.parent_regions.append(pr25)
        sr89.parent_regions.append(pr5)
        sr90.parent_regions.append(pr5)
        sr252.parent_regions.append(pr31)
        sr91.parent_regions.append(pr5)
        sr92.parent_regions.append(pr5)
        sr93.parent_regions.append(pr32)
        sr94.parent_regions.append(pr5)
        sr95.parent_regions.append(pr37)
        sr96.parent_regions.append(pr5)
        sr97.parent_regions.append(pr5)
        sr253.parent_regions.append(pr43)
        sr254.parent_regions.append(pr32)
        sr98.parent_regions.append(pr5)
        sr99.parent_regions.append(pr46)
        sr100.parent_regions.append(pr5)
        sr101.parent_regions.append(pr5)
        sr102.parent_regions.append(pr43)
        sr103.parent_regions.append(pr6)
        sr104.parent_regions.append(pr5)
        sr105.parent_regions.append(pr49)
        sr106.parent_regions.append(pr5)
        sr107.parent_regions.append(pr5)
        sr108.parent_regions.append(pr43)
        sr109.parent_regions.append(pr5)
        sr110.parent_regions.append(pr5)
        sr111.parent_regions.append(pr5)
        sr112.parent_regions.append(pr5)
        sr113.parent_regions.append(pr5)
        sr114.parent_regions.append(pr5)
        sr115.parent_regions.append(pr5)
        sr116.parent_regions.append(pr43)
        sr117.parent_regions.append(pr5)
        sr118.parent_regions.append(pr5)
        sr119.parent_regions.append(pr37)
        sr255.parent_regions.append(pr43)
        sr256.parent_regions.append(pr5)
        sr120.parent_regions.append(pr5)
        sr121.parent_regions.append(pr5)
        sr122.parent_regions.append(pr5)
        sr123.parent_regions.append(pr37)
        sr124.parent_regions.append(pr47)
        sr257.parent_regions.append(pr5)
        sr125.parent_regions.append(pr5)
        sr126.parent_regions.append(pr5)
        sr258.parent_regions.append(pr5)
        sr127.parent_regions.append(pr6)
        sr128.parent_regions.append(pr5)
        sr129.parent_regions.append(pr5)
        sr130.parent_regions.append(pr5)
        sr131.parent_regions.append(pr5)
        sr132.parent_regions.append(pr32)
        sr133.parent_regions.append(pr5)
        sr134.parent_regions.append(pr47)
        sr135.parent_regions.extend([pr33, pr42, pr46])
        sr136.parent_regions.append(pr22)
        sr137.parent_regions.append(pr32)
        sr138.parent_regions.append(pr3)
        sr139.parent_regions.append(pr5)
        sr140.parent_regions.extend([pr12, pr47])
        sr141.parent_regions.append(pr5)
        sr142.parent_regions.append(pr5)
        sr143.parent_regions.append(pr5)
        sr144.parent_regions.append(pr12)
        sr145.parent_regions.append(pr5)
        sr146.parent_regions.append(pr5)
        sr147.parent_regions.extend([pr15, pr25])
        sr148.parent_regions.append(pr5)
        sr149.parent_regions.append(pr5)
        sr150.parent_regions.append(pr5)
        sr151.parent_regions.append(pr5)
        sr152.parent_regions.append(pr5)
        sr153.parent_regions.append(pr5)
        sr154.parent_regions.append(pr5)
        sr155.parent_regions.append(pr5)
        sr156.parent_regions.append(pr5)
        sr157.parent_regions.append(pr5)
        sr158.parent_regions.append(pr5)
        sr259.parent_regions.append(pr5)
        sr159.parent_regions.extend([pr10, pr33])
        sr160.parent_regions.append(pr5)
        sr161.parent_regions.append(pr5)
        sr162.parent_regions.append(pr5)
        sr163.parent_regions.append(pr37)
        sr164.parent_regions.append(pr14)
        sr260.parent_regions.append(pr30)
        sr165.parent_regions.append(pr38)
        sr166.parent_regions.append(pr32)
        sr261.parent_regions.append(pr33)
        sr262.parent_regions.append(pr33)
        sr167.parent_regions.append(pr13)
        sr168.parent_regions.append(pr23)
        sr169.parent_regions.append(pr5)
        sr170.parent_regions.append(pr5)
        sr171.parent_regions.append(pr5)
        sr172.parent_regions.append(pr5)
        sr173.parent_regions.append(pr5)
        sr174.parent_regions.append(pr5)
        sr175.parent_regions.append(pr5)
        sr176.parent_regions.append(pr5)
        sr177.parent_regions.append(pr5)
        sr178.parent_regions.append(pr5)
        sr179.parent_regions.append(pr5)
        sr180.parent_regions.append(pr5)
        sr181.parent_regions.append(pr5)

        sr182.parent_regions.append(pr5)
        sr183.parent_regions.append(pr5)
        sr184.parent_regions.append(pr5)
        sr185.parent_regions.append(pr5)
        sr186.parent_regions.append(pr37)
        sr187.parent_regions.append(pr37)
        sr188.parent_regions.append(pr37)
        sr189.parent_regions.extend([pr37, pr47])
        sr7.parent_regions.append(pr47)
        sr191.parent_regions.append(pr47)
        sr192.parent_regions.append(pr47)
        sr193.parent_regions.append(pr47)
        sr194.parent_regions.append(pr46)
        sr195.parent_regions.append(pr33)
        sr196.parent_regions.append(pr49)
        sr197.parent_regions.extend([pr13, pr15, pr23, pr49])
        sr198.parent_regions.extend([pr12, pr37])
        sr199.parent_regions.append(pr47)
        sr200.parent_regions.append(pr47)
        sr201.parent_regions.append(pr47)
        sr263.parent_regions.append(pr5)
        sr202.parent_regions.append(pr5)
        sr203.parent_regions.append(pr5)
        sr204.parent_regions.append(pr5)
        sr205.parent_regions.append(pr5)
        sr206.parent_regions.append(pr5)
        sr264.parent_regions.append(pr5)
        sr265.parent_regions.append(pr37)
        sr207.parent_regions.append(pr37)
        sr208.parent_regions.append(pr37)
        sr209.parent_regions.append(pr5)
        sr266.parent_regions.append(pr37)
        sr210.parent_regions.append(pr5)
        sr5.parent_regions.append(pr46)
        sr267.parent_regions.append(pr37)
        sr212.parent_regions.append(pr32)
        sr213.parent_regions.append(pr30)
        sr214.parent_regions.append(pr10)
        sr215.parent_regions.append(pr7)
        sr216.parent_regions.append(pr33)
        sr217.parent_regions.append(pr47)
        sr218.parent_regions.append(pr47)
        sr219.parent_regions.append(pr37)
        sr220.parent_regions.append(pr37)
        sr221.parent_regions.append(pr47)
        sr222.parent_regions.append(pr5)
        sr268.parent_regions.append(pr5)
        sr223.parent_regions.append(pr37)
        sr224.parent_regions.append(pr47)
        sr225.parent_regions.append(pr47)
        sr226.parent_regions.append(pr37)
        sr227.parent_regions.append(pr5)
        sr228.parent_regions.append(pr5)
        sr229.parent_regions.append(pr11)
        sr230.parent_regions.append(pr47)
        sr231.parent_regions.append(pr5)
        sr232.parent_regions.append(pr46)
        sr233.parent_regions.append(pr3)
        sr234.parent_regions.append(pr5)
        sr235.parent_regions.append(pr5)
        sr236.parent_regions.append(pr5)
        sr237.parent_regions.append(pr5)
        sr238.parent_regions.append(pr47)
        sr239.parent_regions.append(pr5)
        sr240.parent_regions.append(pr5)
        sr269.parent_regions.append(pr5)
        sr241.parent_regions.append(pr5)
        sr242.parent_regions.append(pr5)
        sr243.parent_regions.append(pr5)
        sr244.parent_regions.append(pr5)

        g1.subregions.extend([sr1, sr4, sr6])
        g2.subregions.extend([sr1, sr2, sr3, sr4, sr5, sr6, sr7])
        g3.subregions.append(sr2)
        g4.subregions.extend([sr1, sr2, sr3, sr4, sr6, sr7])
        g5.subregions.extend([sr1, sr6, sr5]) 
        g6.subregions.extend([sr2, sr7])


        # u1 = User(first_name='Drew', last_name='Hairston', username='dch528', _password_hash='771532Drew!',
        #           email_address='dch528@gmail.com', admin=True)

        # u2 = User(first_name='John', last_name='Doe', username='tester', _password_hash='test123!',
        #           email_address='test@test.com', admin=False)

        # db.session.add_all([g1, g2, g3, g4, g5, g6, pr1, pr2, pr3, pr4, pr5, sr1, sr2, sr3, sr4, sr5, sr6, sr7, u1, u2])
        db.session.add_all([g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14, g15, g16, g17, g18, g19, g20, g21, g22, g23, g24, g25, g26, g27, g28, g29, g30, g31, g32, g33, g34, g35, g36, g37, g38, g39, g40, g41, g42, g43, g44, g45, g46, g47, g48, g49, g50, g51, g52, g53, g54, g55, g56, g57, g58, g59, g60, pr1, pr2, pr3, pr4, pr5, pr6, pr7, pr8, pr9, pr10, pr11, pr12, pr13, pr14, pr15, pr16, pr17, pr18, pr19, pr20, pr21, pr22, pr23, pr24, pr25, pr26, pr27, pr28, pr29, pr30, pr31, pr32, pr33, pr34, pr35, pr36, pr37, pr38, pr39, pr40, pr41, pr42, pr43, pr44, pr45, pr46, pr47, pr48, pr49, pr50, sr1, sr2, sr3, sr4, sr5, sr6, sr7, sr8, sr9, sr10, sr11, sr12, sr13, sr14, sr15, sr16, sr17, sr18, sr19, sr20, sr21, sr22, sr23, sr24, sr25, sr26, sr27, sr28, sr29, sr30, sr31, sr32, sr33, sr34, sr35, sr36, sr37, sr38, sr39, sr40, sr41, sr42, sr43, sr44, sr45, sr46, sr47, sr48, sr49, sr50, sr51, sr52, sr53, sr54, sr55, sr56, sr57, sr58, sr59, sr60, sr61, sr62, sr63, sr64, sr65, sr66, sr67, sr68, sr69, sr70, sr71, sr72, sr73, sr74, sr75, sr76, sr77, sr78, sr79, sr80, sr81, sr82, sr83, sr84, sr85, sr86, sr87, sr88, sr89, sr90, sr91, sr92, sr93, sr94, sr95, sr96, sr97, sr98, sr99, sr100, sr101, sr102, sr103, sr104, sr105, sr106, sr107, sr108, sr109, sr110, sr111, sr112, sr113, sr114, sr115, sr116, sr117, sr118, sr119, sr120, sr121, sr122, sr123, sr124, sr125, sr126, sr127, sr128, sr129, sr130, sr131, sr132, sr133, sr134, sr135, sr136, sr137, sr138, sr139, sr140, sr141, sr142, sr143, sr144, sr145, sr146, sr147, sr148, sr149, sr150, sr151, sr152, sr153, sr154, sr155, sr156, sr157, sr158, sr159, sr160, sr161, sr162, sr163, sr164, sr165, sr166, sr167, sr168, sr169, sr170, sr171, sr172, sr173, sr174, sr175, sr176, sr177, sr178, sr179, sr180, sr181, sr182, sr183, sr184, sr185, sr186, sr187, sr188, sr189, sr191, sr192, sr193, sr194, sr195, sr196, sr197, sr198, sr199, sr200, sr202, sr203, sr204, sr205, sr206, sr207, sr208, sr209, sr210, sr212, sr213, sr214, sr215, sr216, sr217, sr218, sr219, sr220, sr221, sr222, sr223, sr224, sr225, sr226, sr227, sr228, sr229, sr230, sr231, sr232, sr233, sr234, sr235, sr236, sr237, sr238, sr239, sr240, sr241, sr242, sr243, sr244, sr245, sr246, sr247, sr248, sr249, sr250, sr251, sr252, sr253, sr254, sr255, sr256, sr257, sr258, sr259, sr260, sr261, sr262, sr263, sr264, sr265, sr266, sr267, sr268, sr269])
        db.session.commit()