sr245.parent_regions.extend([pr4, pr25, pr36])
sr1.parent_regions.append(pr5)
sr8.parent_regions.append(pr5)
sr9.parent_regions.append(pr5)
sr10.parent_regions.append(pr37)
sr3.parent_regions.append(pr37)
sr11.parent_regions.append(pr5)
sr12.parent_regions.append(pr22)
sr13.parent_regions.append(pr5)
sr2.parent_regions.append(pr32)
sr14.parent_regions.append(pr5)
sr15.parent_regions.append(pr5)
sr16.parent_regions.append(pr5)
sr17.parent_regions.append(pr5)
sr18.parent_regions.append(pr25)
sr19.parent_regions.append(pr5)
sr246.parent_regions.append(pr22)
sr20.parent_regions.append(pr5)
sr21.parent_regions.append(pr5)
sr22.parent_regions.append(pr5)
sr247.parent_regions.append(pr5)
sr23.parent_regions.append(pr5)
sr24.parent_regions.append(pr5)
sr25.parent_regions.append(pr46)
sr26.parent_regions.append(pr38)
sr27.parent_regions.append(pr5)
sr28.parent_regions.append(pr35)
sr29.parent_regions.append(pr5)
sr30.parent_regions.extend([pr30, pr38])
sr31.parent_regions.append(pr43)
sr32.parent_regions.append(pr5)
sr33.parent_regions.append(pr32)
sr34.parent_regions.append(pr5)
sr35.parent_regions.append(pr5)
sr36.parent_regions.append(pr5)
sr37.parent_regions.append(pr5)
sr38.parent_regions.append(pr5)
sr39.parent_regions.append(pr5)
sr40.parent_regions.append(pr5)
sr41.parent_regions.append(pr35)
sr42.parent_regions.append(pr5)
sr43.parent_regions.append(pr46)
sr44.parent_regions.append(pr20)
sr248.parent_regions.append(pr5)
sr45.parent_regions.append(pr20)
sr46.parent_regions.append(pr46)
sr47.parent_regions.append(pr4)
sr48.parent_regions.append(pr5)
sr49.parent_regions.append(pr5)
sr50.parent_regions.append(pr25)
sr51.parent_regions.append(pr22)
sr52.parent_regions.extend([pr14, pr17, pr35, pr48])
sr6.parent_regions.append(pr5)
sr249.parent_regions.append(pr21)
sr53.parent_regions.append(pr5)
sr54.parent_regions.append(pr5)
sr55.parent_regions.append(pr5)
sr56.parent_regions.append(pr5)
sr57.parent_regions.append(pr5)
sr58.parent_regions.append(pr5)
sr59.parent_regions.extend([pr37, pr47])
sr60.parent_regions.extend([pr37, pr47])
sr61.parent_regions.extend([pr32, pr35, pr38])
sr62.parent_regions.append(pr5)
sr63.parent_regions.append(pr5)
sr64.parent_regions.extend([pr7, pr21, pr39])
sr65.parent_regions.append(pr5)
sr66.parent_regions.append(pr5)
sr67.parent_regions.append(pr3)
sr250.parent_regions.append(pr32)
sr68.parent_regions.append(pr5)
sr69.parent_regions.extend([pr31, pr43])
sr70.parent_regions.append(pr5)
sr71.parent_regions.extend([pr18, pr24, pr42])
sr72.parent_regions.append(pr35)
sr73.parent_regions.append(pr37)
sr74.parent_regions.append(pr46)
sr251.parent_regions.append(pr32)
sr75.parent_regions.append(pr5)
sr76.parent_regions.append(pr5)
sr77.parent_regions.append(pr48)
sr78.parent_regions.append(pr4)
sr79.parent_regions.append(pr31)
sr80.parent_regions.extend([pr20, pr38])
sr81.parent_regions.append(pr5)
sr82.parent_regions.append(pr22)
sr83.parent_regions.append(pr5)
sr84.parent_regions.append(pr5)
sr85.parent_regions.append(pr7)
sr86.parent_regions.append(pr5)
sr87.parent_regions.append(pr30)
sr88.parent_regions.append(pr25)
sr89.parent_regions.append(pr5)
sr90.parent_regions.append(pr5)
sr252.parent_regions.append(pr31)
sr91.parent_regions.append(pr5)
sr92.parent_regions.append(pr5)
sr93.parent_regions.append(pr32)
sr94.parent_regions.append(pr5)
sr95.parent_regions.append(pr37)
sr96.parent_regions.append(pr5)
sr97.parent_regions.append(pr5)
sr253.parent_regions.append(pr43)
sr254.parent_regions.append(pr32)
sr98.parent_regions.append(pr5)
sr99.parent_regions.append(pr46)
sr100.parent_regions.append(pr5)
sr101.parent_regions.append(pr5)
sr102.parent_regions.append(pr43)
sr103.parent_regions.append(pr6)
sr104.parent_regions.append(pr5)
sr105.parent_regions.append(pr49)
sr106.parent_regions.append(pr5)
sr107.parent_regions.append(pr5)
sr108.parent_regions.append(pr43)
sr109.parent_regions.append(pr5)
sr110.parent_regions.append(pr5)
sr111.parent_regions.append(pr5)
sr112.parent_regions.append(pr5)
sr113.parent_regions.append(pr5)
sr114.parent_regions.append(pr5)
sr115.parent_regions.append(pr5)
sr116.parent_regions.append(pr43)
sr117.parent_regions.append(pr5)
sr118.parent_regions.append(pr5)
sr119.parent_regions.append(pr37)
sr255.parent_regions.append(pr43)
sr256.parent_regions.append(pr5)
sr120.parent_regions.append(pr5)
sr121.parent_regions.append(pr5)
sr122.parent_regions.append(pr5)
sr123.parent_regions.append(pr37)
sr124.parent_regions.append(pr47)
sr257.parent_regions.append(pr5)
sr125.parent_regions.append(pr5)
sr126.parent_regions.append(pr5)
sr258.parent_regions.append(pr5)
sr127.parent_regions.append(pr6)
sr128.parent_regions.append(pr5)
sr129.parent_regions.append(pr5)
sr130.parent_regions.append(pr5)
sr131.parent_regions.append(pr5)
sr132.parent_regions.append(pr32)
sr133.parent_regions.append(pr5)
sr134.parent_regions.append(pr47)
sr135.parent_regions.extend([pr33, pr42, pr46])
sr136.parent_regions.append(pr22)
sr137.parent_regions.append(pr32)
sr138.parent_regions.append(pr3)
sr139.parent_regions.append(pr5)
sr140.parent_regions.extend([pr12, pr47])
sr141.parent_regions.append(pr5)
sr142.parent_regions.append(pr5)
sr143.parent_regions.append(pr5)
sr144.parent_regions.append(pr12)
sr145.parent_regions.append(pr5)
sr146.parent_regions.append(pr5)
sr147.parent_regions.extend([pr15, pr25])
sr148.parent_regions.append(pr5)
sr149.parent_regions.append(pr5)
sr150.parent_regions.append(pr5)
sr151.parent_regions.append(pr5)
sr152.parent_regions.append(pr5)
sr153.parent_regions.append(pr5)
sr154.parent_regions.append(pr5)
sr155.parent_regions.append(pr5)
sr156.parent_regions.append(pr5)
sr157.parent_regions.append(pr5)
sr158.parent_regions.append(pr5)
sr259.parent_regions.append(pr5)
sr159.parent_regions.extend([pr10, pr33])
sr160.parent_regions.append(pr5)
sr161.parent_regions.append(pr5)
sr162.parent_regions.append(pr5)
sr163.parent_regions.append(pr37)
sr164.parent_regions.append(pr14)
sr260.parent_regions.append(pr30)
sr165.parent_regions.append(pr38)
sr166.parent_regions.append(pr32)
sr261.parent_regions.append(pr33)
sr262.parent_regions.append(pr33)
sr167.parent_regions.append(pr13)
sr168.parent_regions.append(pr23)
sr169.parent_regions.append(pr5)
sr170.parent_regions.append(pr5)
sr171.parent_regions.append(pr5)
sr172.parent_regions.append(pr5)
sr173.parent_regions.append(pr5)
sr174.parent_regions.append(pr5)
sr175.parent_regions.append(pr5)
sr176.parent_regions.append(pr5)
sr177.parent_regions.append(pr5)
sr178.parent_regions.append(pr5)
sr179.parent_regions.append(pr5)
sr180.parent_regions.append(pr5)
sr181.parent_regions.append(pr5)

sr182.parent_regions.append(pr5)
sr183.parent_regions.append(pr5)
sr184.parent_regions.append(pr5)
sr185.parent_regions.append(pr5)
sr186.parent_regions.append(pr37)
sr187.parent_regions.append(pr37)
sr188.parent_regions.append(pr37)
sr189.parent_regions.extend([pr37, pr47])
sr7.parent_regions.append(pr47)
sr191.parent_regions.append(pr47)
sr192.parent_regions.append(pr47)
sr193.parent_regions.append(pr47)
sr194.parent_regions.append(pr46)
sr195.parent_regions.append(pr33)
sr196.parent_regions.append(pr49)
sr197.parent_regions.extend([pr13, pr15, pr23, pr49])
sr198.parent_regions.extend([pr12, pr37])
sr199.parent_regions.append(pr47)
sr200.parent_regions.append(pr47)
sr201.parent_regions.append(pr47)
sr263.parent_regions.append(pr5)
sr202.parent_regions.append(pr5)
sr203.parent_regions.append(pr5)
sr204.parent_regions.append(pr5)
sr205.parent_regions.append(pr5)
sr206.parent_regions.append(pr5)
sr264.parent_regions.append(pr5)
sr265.parent_regions.append(pr37)
sr207.parent_regions.append(pr37)
sr208.parent_regions.append(pr37)
sr209.parent_regions.append(pr5)
sr266.parent_regions.append(pr37)
sr210.parent_regions.append(pr5)
sr5.parent_regions.append(pr46)
sr267.parent_regions.append(pr37)
sr212.parent_regions.append(pr32)
sr213.parent_regions.append(pr30)
sr214.parent_regions.append(pr10)
sr215.parent_regions.append(pr7)
sr216.parent_regions.append(pr33)
sr217.parent_regions.append(pr47)
sr218.parent_regions.append(pr47)
sr219.parent_regions.append(pr37)
sr220.parent_regions.append(pr37)
sr221.parent_regions.append(pr47)
sr222.parent_regions.append(pr5)
sr268.parent_regions.append(pr5)
sr223.parent_regions.append(pr37)
sr224.parent_regions.append(pr47)
sr225.parent_regions.append(pr47)
sr226.parent_regions.append(pr37)
sr227.parent_regions.append(pr5)
sr228.parent_regions.append(pr5)
sr229.parent_regions.append(pr11)
sr230.parent_regions.append(pr47)
sr231.parent_regions.append(pr5)
sr232.parent_regions.append(pr46)
sr233.parent_regions.append(pr3)
sr234.parent_regions.append(pr5)
sr235.parent_regions.append(pr5)
sr236.parent_regions.append(pr5)
sr237.parent_regions.append(pr5)
sr238.parent_regions.append(pr47)
sr239.parent_regions.append(pr5)
sr240.parent_regions.append(pr5)
sr269.parent_regions.append(pr5)
sr241.parent_regions.append(pr5)
sr242.parent_regions.append(pr5)
sr243.parent_regions.append(pr5)
sr244.parent_regions.append(pr5)




#   console.log('bb_regions', bb_regions)
#   console.log('polygon', polygons[0].geometry.coordinates[0][0][0])
#   console.log('multiPolygons', multiPolygons[0], multiPolygons[1], multiPolygons[2])

#   console.log('multipolygon_names', multiPolygons.map((mp)=>mp.properties.Name))
#   console.log('polygon_names', polygons.map((p)=>p.properties.Name))

#   console.log('testy', avaData.features[0])
#   console.log('first_multiPolygon', multiPolygons[0], multiPolygons[12], multiPolygons[20])
#   console.log('first_polygon', polygons[0], polygons[1], polygons[87])

# console.log('ln',  Object.keys(avaData['features']).length)
# console.log('ln', avaData['features'][0])


# const stateArr = []

# stateArr.push(

# console.log('NAMES', avaData['features'].map((ft)=> stateArr.push( { name: ft['properties']['Name'], states: ft['properties']['States'] } )))
# const avaDataNamesAndStates = avaData['features'].map((ft) => (
  
#   stateArr.push( { name: ft['properties']['Name'], states: ft['properties']['States'] } ))
# )
# names and states of avadata
# get subregions , match with statearr by name
# get subregions, match with statearr by statearr.states.inlucdes sr.name 


# subregions find id of region that matches avadata subregion, match to id of state that matches avadata states
# const allAvaStuff = []
# stateArr.map((ava) => {
# allAvaStuff.push({subRegion: sr1.filter((sr)=>sr.name == ava.name), parentRegion: pr1.filter((pr)=>ava.states.includes(pr.abbreviation))})
# })

# console.log('allAVASTUFF',allAvaStuff)
# console.log('allAVASTUFF@', allAvaStuff.map((ava)=>  'sr' + ava.subRegion[0]?.id + '.parent_regions = ' + ava.parentRegion.map((pr) =>pr.id)))
# console.log('allAVASTUFF2', allAvaStuff.map((ava)=>  'sr' + ava.subRegion[0]?.id + '.parent_regions.'  + (ava.parentRegion.length == 1 ? 'append(pr' + (ava.parentRegion.map((pr) =>pr.id)) + ')': 'extend([pr' + (ava.parentRegion.map((pr) =>pr.id)).join(', pr') + '])')))
# console.log('allAVASTUFF3', allAvaStuff.map((ava)=>ava.parentRegion.length == 1))

# console.log('stateArr', stateArr)
# console.log('STATES', avaData['features'].map((ft)=>ft['properties']['States'] ))
# get the states that subregions are contained in in geojson with the subregion name
# concat 

# console.log('sr1', sr1.map((reg) => reg.name))

# console.log("NS", )



  <div>
          {Object.entries(selectedAVA).slice(1, 3).map((prop) => (
            <Popup
              // latitude={selectedAVA.geometry.type == 'MultiPolygon' ? selectedAVA.geometry.coordinates[0][0][0][1] : selectedAVA.geometry.coordinates[0][0][1]  }
              // longitude={selectedAVA.geometry.type == 'MultiPolygon' ?  selectedAVA.geometry.coordinates[0][0][0][0] :  selectedAVA.geometry.coordinates[0][0][0]}
              longitude={-100} latitude={40}
              anchor="bottom"
            // onClose={() => {
            //   setSelectedAVA(null);
            // }}
            >
              {console.log('ptop', prop[0] == 'properties' ? prop[1].Name  : null)}
              {console.log('ptop2', prop)}
              <div className='popup'>
                <h1>Hello</h1>
                {prop[0] == 'properties' ? <h2> prop[1].Name </h2> : null}
                {/* <h2>{selectedAVA[keyName]}</h2> */}
                {/* <p>{selectedAVA.properties.States}</p>  */}
              </div>
            </Popup>


          )

)}
        </div>