"""Initial Migration

Revision ID: 857bf0463a52
Revises: 
Create Date: 2024-05-08 23:24:51.998754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857bf0463a52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parent_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subregions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('climate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('username')
    )
    op.create_table('grapes_subregions',
    sa.Column('grape_id', sa.Integer(), nullable=False),
    sa.Column('subregions_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grape_id'], ['grapes.id'], name=op.f('fk_grapes_subregions_grape_id_grapes')),
    sa.ForeignKeyConstraint(['subregions_id'], ['subregions.id'], name=op.f('fk_grapes_subregions_subregions_id_subregions')),
    sa.PrimaryKeyConstraint('grape_id', 'subregions_id')
    )
    op.create_table('parentregion_subregions',
    sa.Column('parentregions_id', sa.Integer(), nullable=False),
    sa.Column('subregions_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parentregions_id'], ['parent_regions.id'], name=op.f('fk_parentregion_subregions_parentregions_id_parent_regions')),
    sa.ForeignKeyConstraint(['subregions_id'], ['subregions.id'], name=op.f('fk_parentregion_subregions_subregions_id_subregions')),
    sa.PrimaryKeyConstraint('parentregions_id', 'subregions_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parentregion_subregions')
    op.drop_table('grapes_subregions')
    op.drop_table('users')
    op.drop_table('subregions')
    op.drop_table('parent_regions')
    op.drop_table('grapes')
    # ### end Alembic commands ###
